### ISSUE TITLE
getting error while passing props to ckeditor component 

### ISSUE THREAD

**Issue by ssonupatra11** [ckeditor/ckeditor4-react#179]
Hello, i am facing some problems while using CKeditor with react and typescript. i have imported the ckeditor in my react component but while adding props like name,readOnly,onChange and some other properties to the CKeditor component it is showing error.

**Here i am writing my code.....**
```

import * as React from 'react'
import CKEditor from 'ckeditor4-react'
import ckeditor from './ckeditor.css'
interface Props {
  properties: object
  options?: object
  data?: string
  defaultValue?: string
  identifier: string
}

export const CKeditor = ({
  properties = {},
  //options = {},
  identifier
}: Props) => {
  console.log(properties)
  return (
    <div className={ckeditor.main_div}>
      <CKEditor data='' key={identifier} readOnly/>
    </div>
  )
}

```
**Below is the error**
No overload matches this call.
  Overload 1 of 2, '(props: CKEditorProps | Readonly<CKEditorProps>): CKEditor', gave the following error.
    Type '{ data: string; key: string; readOnly: true; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<CKEditor> & Readonly<CKEditorProps> & Readonly<...>'.
      Property 'readOnly' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<CKEditor> & Readonly<CKEditorProps> & Readonly<...>'.
  Overload 2 of 2, '(props: CKEditorProps, context: any): CKEditor', gave the following error.
    Type '{ data: string; key: string; readOnly: true; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<CKEditor> & Readonly<CKEditorProps> & Readonly<...>'.
      Property 'readOnly' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<CKEditor> & Readonly<CKEditorProps> & Readonly<...>'.ts(2769) 

i am using react version 17, and ckeditor4 .

Thanks in advance.

**Comment by sculpt0r** [comment]
Hi @ssonupatra11 

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).

Also, please notice that our integration works with react 16.0.0 (https://github.com/ckeditor/ckeditor4-react/blob/d2552a60019d13f3bfcd6504800826be45736115/package.json#L50). It also looks like you have some troubles with types, please take a look at #82
